[package]
name = "kbm-gamepad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.12.2"
lazy_static = "1.4.0"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
