[general_settings]
read_mouse_events = true
read_kbd_events = false

[gamepad_settings]
range = 1024
fuzz = 0
flat = 0
resolution = 1

[bindings]
north = "w"
east = "a"
south = "s"
west = "d"
dpad_up = "up"
dpad_down = "down"
dpad_left = "left"
dpad_right = "right"
select = "x"
start = "c"
l1 = "q"
l2 = "leftshift"
r1 = "e"
r2 = "f"
